### ISSUE TITLE
reporting outdated answers

### ISSUE THREAD

**Issue by lgriffith3428** [yarneo/telegram-trivia-bot#1]
![1435591253495](https://cloud.githubusercontent.com/assets/13104474/8411383/b0a757ca-1e7b-11e5-8c83-252ee7e7808d.jpg)

**Comment by yarneo** [comment]
Hey staringgirl,

Thanks for your feedback but actually that screenshot you took is of the triviabot created by Telegram and not by me. The one here has a bigger database of questions that doesn't only include multiple choice questions :)
