### ISSUE TITLE
error for some imported package

### ISSUE THREAD

**Issue by svfnix** [yarneo/telegram-trivia-bot#3]
hi
some of imported package like org.telegram.api.TLConfig not found so i cant run this app.
where can i download  this packages?

**Comment by yarneo** [comment]
Hey svfnix! I will update the repo tonight. Sorry it took me so long, let me know if after the push you are still having problems

**Comment by yarneo** [comment]
hopefully now you can set up the trivia bot easier with the latest update, have a look at the readme and let me know if you are still having issues.
